# Generated by Django 4.1 on 2022-09-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendencemanagementsystems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(blank=True, choices=[(1, 'Admin'), (2, 'Teacher'), (3, 'Student')], default=3),
        ),
    ]
