# Generated by Django 4.1 on 2022-09-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendencemanagementsystems', '0004_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[(1, 'Admin'), (2, 'Teacher'), (3, 'Student')], default=3, max_length=15),
        ),
    ]
