# Generated by Django 4.1 on 2022-09-28 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendencemanagementsystems', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
